package org.test;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class RollingFileTest {
	private static Logger logger = LogManager.getLogger();
	
    public boolean someLibraryMethod() {
        for (int i = 0; i < 1000; i++) {
        	logger.info("I'm here" + i);
		}
        return true;
    }
    
    public static void main(String[] args) {
		new RollingFileTest().someLibraryMethod();
	}
}
